# tpo_playbook.v1.yaml
schema: tpo_playbook.v1
version: 1

# Key = "day_type,ib_side,ib_acceptance,gap_closed,dominant_evidence"
# day_type: D|P|b|B
# ib_side: Up|Down|None
# ib_acceptance: true|false           # our v9.2x acceptance test (>=0.25xIB & holds)
# gap_closed: true|false              # first touch of prior RTH close by cutoff
# dominant_evidence: E_* tag from v9.2c (e.g., E_DPOC_RUN_DOWN)

plays:

  # ========= BALANCED DAY TILTING DOWN (common) =========
  "D,Down,false,true,E_DPOC_RUN_DOWN":
    name: "Balanced → downside tilt (gap closed)"
    checklist:
      - "Bias short into **LVN below**; use **POC** as risk reference"
      - "Favor entries on **IB mid/IBL retests** or weak bounces"
      - "Avoid chasing if price returns **inside VA** quickly"
    targets: ["Nearest LVN below", "VAL − 0.3×IB", "Prior session HVN"]
    invalidations: ["Close back **inside IB**", "POC shifts up to **middle third**", "DPOC returns to VA next bracket"]
    management: ["Trail above prior bracket **high**", "Reduce risk after LVN reaction"]
    confidence: med
    notes: "DPOC run ≈ value migration down; gap closed removes mean-reversion pressure."

  "D,Down,false,false,E_DPOC_RUN_DOWN":
    name: "Balanced → downside tilt (gap open)"
    checklist:
      - "Favor shorts toward **gap-fill** & lower LVNs"
      - "If gap refuses to close on first attempt, keep a runner"
    targets: ["Gap-fill price", "LVN below", "VAL − 0.5×IB"]
    invalidations: ["Strong **IB re-entry** & close above IBL", "DPOC back inside VA"]
    management: ["Trail above prior bracket high", "Trim into gap-fill reaction"]
    confidence: med
    notes: "Open gap can serve as magnet but can also sustain trend if not filling quickly."

  # ========= BALANCED DAY TILTING UP =========
  "D,Up,false,true,E_DPOC_RUN_UP":
    name: "Balanced → upside tilt (gap closed)"
    checklist:
      - "Bias long on **IBH/POC retests** or shallow dips into LVN"
    targets: ["Nearest LVN above", "VAH + 0.3×IB"]
    invalidations: ["Close back **inside IB**", "POC shifts down to middle third"]
    management: ["Trail below prior bracket **low**"]
    confidence: med
    notes: "DPOC run up signals building value higher; gap closed removes fade pressure."

  "D,Up,false,false,E_DPOC_RUN_UP":
    name: "Balanced → upside tilt (gap open)"
    checklist:
      - "Favor longs **toward gap-fill** then VAH"
    targets: ["Gap-fill price", "VAH + 0.5×IB"]
    invalidations: ["IB re-entry and close under IBH", "DPOC snaps back inside VA"]
    management: ["Trail below prior bracket low"]
    confidence: med
    notes: "Open up-gap may either fill or persist; trade with structure."

  # ========= ACCEPTED IB BREAK (trend/initiative) =========
  "D,Up,true,*,E_DPOC_OUTSIDE_IB_UP":
    name: "Accepted above IB (initiative up)"
    checklist:
      - "Buy **pullbacks above IBH** (acceptance zone)"
      - "If single prints form below, place invalidation beneath them"
    targets: ["VAH extension", "Prior session HVN above"]
    invalidations: ["Close back **inside IB**", "One-timeframing **Down** starts"]
    management: ["Trail below last single-print base or prior bracket low"]
    confidence: high
    notes: "Per IB play: extension that **holds** outside IB indicates acceptance, not probe."

  "D,Down,true,*,E_DPOC_OUTSIDE_IB_DOWN":
    name: "Accepted below IB (initiative down)"
    checklist:
      - "Sell **bounces below IBL**; respect acceptance zone"
      - "Use single-print caps above for invalidation"
    targets: ["VAL extension", "Prior session HVN below"]
    invalidations: ["Close back **inside IB**", "One-timeframing **Up** starts"]
    management: ["Trail above last single-print cap or prior bracket high"]
    confidence: high
    notes: "Acceptance below IBL → price is being **accepted** lower."

  # ========= REJECTION AFTER PUSH =========
  "*,*,*,*,E_DPOC_RETURN_TO_VA":
    name: "Rejection—back inside value"
    checklist:
      - "Fade pushes back toward **POC** / opposite VA edge"
      - "Take profits at **POC/HVN**; expect balance"
    targets: ["POC", "Opposite VA edge"]
    invalidations: ["DPOC resumes run outside VA", "Fresh single prints against the fade"]
    management: ["Flat into POC reaction if rotation weakens"]
    confidence: low
    notes: "Outside push failed to hold; revert to balance expectations."

  # ========= DOUBLE-DISTRIBUTION RISK =========
  "B,*,false,*,E_DOUBLE_DISTRIBUTION_RISK":
    name: "Developing double-distribution (B-type risk)"
    checklist:
      - "Trade **between distributions**: fade into LVN, target opposing HVN"
      - "If DPOC shifts to upper node, switch bias to that node"
    targets: ["Upper/Lower **HVN**", "LVN midpoint"]
    invalidations: ["Acceptance inside the **split LVN** (no longer rejection)", "POC consolidates in middle third"]
    management: ["Reduce size in middle; add only at node edges"]
    confidence: med
    notes: "Two nodes forming; LVN acts as divider. Expect rotations."

  # ========= CLASSIC P/b DAYS (excess tail + value skew) =========
  "P,*,*,*,E_STABLE_DPOC_IN_VALUE":
    name: "P-day bias (excess low, distribution higher)"
    checklist:
      - "Lean long on **VAL retests**; avoid chasing into VAH"
    targets: ["POC", "VAH"]
    invalidations: ["POC shifts down to middle third", "Strong IB re-entry down"]
    management: ["Trail below VAL"]
    confidence: med

  "b,*,*,*,E_STABLE_DPOC_IN_VALUE":
    name: "b-day bias (excess high, distribution lower)"
    checklist:
      - "Lean short on **VAH retests**; avoid chasing into VAL"
    targets: ["POC", "VAL"]
    invalidations: ["POC shifts up to middle third", "Strong IB re-entry up"]
    management: ["Trail above VAH"]
    confidence: med

